/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gymapp.view;

import gymapp.utility.Helper;
import gymapp.utility.HibernateUtility;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author frank
 */
public class SplashScreen extends javax.swing.JFrame {

    private int i = 0;
    private boolean hibernateDone;

    public SplashScreen() {
        initComponents();
        Loading loading = new Loading();
        loading.start();
        setTitle(Helper.getTitle(""));
    }

    private class Loading extends Thread {

        @Override
        public void run() {
            Session s = HibernateUtility.getSession();
            if (s.getMetamodel().getEntities().size() > 0) {
                hibernateDone = true;
                for (int t = i; t < 100; t++) {
                    try {
                        Thread.sleep(50);
                        LoadingBar.setValue(++i);
                        LoadingValue.setText(t + "%");

                        if (t == 20) {
                            LoadingLabel.setText("Turning On Modules...");
                        }
                        if (t == 40) {
                            LoadingLabel.setText("Loading Modules...");
                        }
                        if (t == 60) {
                            LoadingLabel.setText("Connection to Database...");
                        }
                        if (t == 80) {
                            LoadingLabel.setText("Launching Application");
                        }
                        LoadingBar.setValue(t);
                    } catch (Exception e) {
                    }
                }
                new Authorization().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "Problem with connecting to the Database.");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPanel = new javax.swing.JPanel();
        BackGroundImage = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        LoadingLabel = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BackGroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackGroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        BackGroundPanel.setMinimumSize(new java.awt.Dimension(900, 500));
        BackGroundPanel.setPreferredSize(new java.awt.Dimension(800, 400));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreen.png"))); // NOI18N
        BackGroundPanel.add(BackGroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 610, 350));
        BackGroundPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 770, -1));

        LoadingLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(51, 51, 51));
        LoadingLabel.setText("Loading...");
        BackGroundPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 250, 30));

        LoadingValue.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(51, 51, 51));
        LoadingValue.setText("0 %");
        BackGroundPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundImage;
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    // End of variables declaration//GEN-END:variables
}
